name: spei-reconstruction-v2
channels:
  - conda-forge
dependencies:
  - python=3.13
  - gdal=3.11.4
  - lightgbm=4.6.0
  - matplotlib=3.10.9
  - netcdf4=1.7.4
  - numpy=2.4.6
  - pandas=3.0.3
  - rasterio=1.5.0
  - scikit-learn=1.8.0
  - scipy=1.17.1
  - xarray=2026.2.0
  - pip
  - pip:
      - remotezip==0.12.6
